### ISSUE TITLE
Bug: after upgrade to 4.x, i got a lot of Typescript Errors

### ISSUE THREAD

**Issue by angelica-snowit** [fnando/i18n#47]
After upgrading to the latest version, i got a lot of typescript errors.

TS2551: Property 'locale' does not exist on type 'typeof import("/node_modules/i18n-js/typings/index")'. Did you mean 'Locales'?
TS2339: Property 't' does not exist on type 'typeof import("/node_modules/i18n-js/typings/index")'.

I've tried to remove @types/i18n-js, but nothing has changed.

**Comment by fnando** [comment]
Are you migrating from v3? If so, you need to migrate your code base to make it work with the new API.

https://github.com/fnando/i18n-js/blob/main/MIGRATING_FROM_V3_TO_V4.md

**Comment by angelica-snowit** [comment]
Thank you, I missed this guide!
